# Generated by Django 5.1.2 on 2025-10-19 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0022_salon_platform_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/photos/')),
                ('type', models.CharField(choices=[('tour', 'Tour'), ('event', 'Event'), ('training', 'Training'), ('other', 'Other')], default='event', max_length=10)),
                ('link', models.URLField(blank=True, null=True)),
                ('organizer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organizer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(max_length=50)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('has_multiple_tariffs', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='EventTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='events/tariffs/')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('price', models.JSONField(default=dict)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden')], default='active', max_length=10)),
                ('availability_type', models.CharField(choices=[('weekly', 'Weekly'), ('specific_dates', 'Specific Dates')], default='weekly', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('specific_dates', models.JSONField(blank=True, default=list)),
                ('months', models.JSONField(blank=True, default=list)),
                ('max_people', models.IntegerField(default=0)),
                ('parallel_events', models.IntegerField(default=0)),
                ('requires_time', models.BooleanField(default=False)),
                ('time_slots', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('participants_count', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('website', 'Website'), ('telegram', 'Telegram'), ('partner_api', 'Partner API')], default='website', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.eventtariff')),
            ],
        ),
    ]
