# Generated by Django 5.1.2 on 2025-10-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtariff',
            name='requires_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
