# Generated by Django 5.1.1 on 2024-10-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salons',
            name='salon_name',
            field=models.CharField(max_length=20, verbose_name='Salon name'),
        ),
    ]
