# Generated by Django 5.1.2 on 2024-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
