# Generated by Django 5.1.2 on 2024-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linked_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password'), ('google', 'Google')], default='password', max_length=20),
        ),
    ]
