# Generated by Django 5.1.2 on 2024-12-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_linked_email_profile_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='linked_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='google_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
