# Generated by Django 5.1.2 on 2024-12-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_profile_linked_email_profile_google_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password'), ('google', 'Google')], max_length=20),
        ),
    ]
