# Generated by Django 5.1.2 on 2025-01-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_profile_telegram_profile_telegram_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push',
            field=models.BooleanField(default=False),
        ),
    ]
