# Generated by Django 5.1.2 on 2025-01-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_profile_push'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='push',
            new_name='push_subscribe',
        ),
    ]
