# Generated by Django 5.1.2 on 2025-01-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_profile_push_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='telegram',
            new_name='whatsapp',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='telegram_phone_number',
            new_name='whatsapp_phone_number',
        ),
    ]
