# Generated by Django 5.1.2 on 2025-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_telegram_profile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
