# Generated by Django 5.1.2 on 2025-01-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_profile_otp_code_profile_otp_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notes',
        ),
    ]
