# Generated by Django 5.1.2 on 2025-01-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_profile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password'), ('google', 'Google'), ('sms', 'SMS')], default='password', max_length=20),
        ),
    ]
