# Generated by Django 5.1.2 on 2025-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_profile_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='push_subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
