# Generated by Django 5.1.2 on 2025-01-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('default_duration', models.IntegerField(default=15, verbose_name='Default duration (minutes)')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='salons/barbers')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentBarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='salons.appointment')),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentbarberservice', to='salons.barber')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='barbers',
            field=models.ManyToManyField(related_name='appointments', through='salons.AppointmentBarberService', to='salons.barber'),
        ),
        migrations.CreateModel(
            name='BarberAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='salons.barber')),
            ],
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Service name', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='salons/barberservices')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='active', max_length=10, verbose_name='Status')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='salons.barber')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_services', to='salons.servicecategory')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentbarberservice',
            name='barberServices',
            field=models.ManyToManyField(blank=True, to='salons.barberservice'),
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Salon name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='salon_logos/', verbose_name='Logo')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('coordinates', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordinates')),
                ('default_duration', models.IntegerField(default=20, verbose_name='Default duration (minutes)')),
                ('default_price', models.DecimalField(decimal_places=0, default=2000, max_digits=15, verbose_name='Default price')),
                ('services_hy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Services_hy')),
                ('services_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Services_ru')),
                ('services_eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='Services_eng')),
                ('shortDescription_hy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short description_hy')),
                ('shortDescription_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short description_ru')),
                ('shortDescription_eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short description_eng')),
                ('description_hy', models.TextField(blank=True, verbose_name='description_hy')),
                ('description_ru', models.TextField(blank=True, verbose_name='description_ru')),
                ('description_eng', models.TextField(blank=True, verbose_name='description_eng')),
                ('reservDays', models.IntegerField(default=9, verbose_name='Reserv days')),
                ('mod', models.CharField(choices=[('category', 'Category'), ('barber', 'Barber')], default='category', max_length=10)),
                ('IsCheckDays', models.BooleanField(default=True, verbose_name='Is Check Days')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('suspend', 'Suspend'), ('disable', 'Disable')], default='new', max_length=10, verbose_name='Status')),
                ('admins', models.ManyToManyField(blank=True, related_name='administered_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salons',
            },
        ),
        migrations.AddField(
            model_name='barber',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.salon'),
        ),
        migrations.CreateModel(
            name='SalonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salons/salons')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='salons/services')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='active', max_length=10, verbose_name='Status')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salons.salon')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='salons.servicecategory')),
            ],
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='salons.service'),
        ),
        migrations.AddField(
            model_name='appointmentbarberservice',
            name='services',
            field=models.ManyToManyField(blank=True, to='salons.service'),
        ),
        migrations.AddField(
            model_name='barber',
            name='categories',
            field=models.ManyToManyField(related_name='barbers', to='salons.servicecategory'),
        ),
    ]
