# Generated by Django 5.1.1 on 2024-10-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='coordinates',
            field=models.CharField(default=(40.20881386242321, 44.52516312701523), max_length=50, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salons',
            name='salon_name',
            field=models.CharField(max_length=20, verbose_name='Salon name'),
        ),
    ]
