# Generated by Django 5.1.2 on 2025-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='default_duration',
            field=models.IntegerField(default=20, verbose_name='Default duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='barberservice',
            name='duration',
            field=models.DurationField(blank=True, default=20, null=True),
        ),
    ]
