# Generated by Django 5.1.2 on 2024-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/services'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='salons/barbers'),
        ),
        migrations.AlterField(
            model_name='salonimage',
            name='image',
            field=models.ImageField(upload_to='salons/salons'),
        ),
    ]
