# Generated by Django 5.1.1 on 2024-10-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salons_coordinates_alter_salons_salon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salons',
            name='coordinates',
            field=models.CharField(max_length=50, verbose_name='Coordinates'),
        ),
    ]
