# Generated by Django 5.1.2 on 2024-11-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_service_image_alter_barber_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='salon',
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
