# Generated by Django 5.1.1 on 2024-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_alter_salons_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salons',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordinates'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='salon_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='salon_name',
            field=models.CharField(max_length=50, verbose_name='Salon name'),
        ),
    ]
