# Generated by Django 5.1.2 on 2024-11-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_remove_servicecategory_salon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
