# Generated by Django 5.1.2 on 2025-01-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_barber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='telegram_appointmentMod',
            field=models.CharField(choices=[('services', 'Services'), ('barbers', 'Barbers')], default='services', max_length=10, verbose_name='Telegram Appointment Mod'),
        ),
        migrations.AddField(
            model_name='salon',
            name='telegram_barbersMod',
            field=models.CharField(choices=[('without_images', 'Without images'), ('with_images', 'With images')], default='services', max_length=15, verbose_name='Telegram Barbers Bod'),
        ),
    ]
