# Generated by Django 5.1.1 on 2024-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_alter_salons_address_alter_salons_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='salon_images/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
