# Generated by Django 5.1.2 on 2025-02-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_salon_telegram_appointmentmod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='appointment_mod',
            field=models.CharField(choices=[('handle', 'Handle'), ('auto', 'Auto')], default='handle', max_length=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='telegram_status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('suspend', 'Suspend'), ('disable', 'Disable')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='salon',
            name='telegram_barbersMod',
            field=models.CharField(choices=[('without_images', 'Without images'), ('with_images', 'With images')], default='without_images', max_length=15, verbose_name='Telegram Barbers Bod'),
        ),
    ]
