# Generated by Django 5.1.2 on 2025-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salon_appointment_mod_salon_telegram_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='appointment_mod',
            field=models.CharField(choices=[('handle', 'Handle'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
    ]
