# Generated by Django 5.1.2 on 2024-11-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_appointment_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='salons.service'),
        ),
    ]
