# Generated by Django 5.1.2 on 2025-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_alter_salon_appointment_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
