# Generated by Django 5.1.2 on 2024-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_remove_salons_description_salons_description_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='services_eng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Services_hy'),
        ),
        migrations.AddField(
            model_name='salons',
            name='services_hy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Services_hy'),
        ),
        migrations.AddField(
            model_name='salons',
            name='services_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Services_hy'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='description_eng',
            field=models.TextField(blank=True, verbose_name='description_eng'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='description_hy'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='description_ru'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='shortDescription_eng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short description_eng'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='shortDescription_hy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short description_hy'),
        ),
        migrations.AlterField(
            model_name='salons',
            name='shortDescription_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short description_ru'),
        ),
    ]
