# Generated by Django 5.1.2 on 2024-11-05 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_alter_appointment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['salon', 'date', 'start_time', 'end_time'], name='salons_appo_salon_i_86cbcc_idx'),
        ),
    ]
