# Generated by Django 5.1.2 on 2025-02-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_barberservice_description_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend'), ('disable', 'Disable')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
