# Generated by Django 5.1.2 on 2025-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0009_salon_instagram_salon_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
    ]
