# Generated by Django 5.1.2 on 2024-10-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0009_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='salon_name',
            new_name='name',
        ),
    ]
