# Generated by Django 5.1.2 on 2024-11-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_alter_appointment_start_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentBarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='salons_appo_salon_i_fd1935_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointmentbarberservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='salons.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentbarberservice',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salons.barber'),
        ),
        migrations.AddField(
            model_name='appointmentbarberservice',
            name='services',
            field=models.ManyToManyField(to='salons.service'),
        ),
    ]
