# Generated by Django 5.1.2 on 2024-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_rename_salon_name_salons_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('suspend', 'Suspend'), ('disable', 'Disable')], default='new', max_length=10, verbose_name='Status'),
        ),
    ]
