# Generated by Django 5.1.2 on 2024-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0011_salons_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='default_duration',
            field=models.IntegerField(default=20, verbose_name='Default duration (minutes)'),
        ),
        migrations.AddField(
            model_name='salons',
            name='default_price',
            field=models.DecimalField(decimal_places=0, default=2000, max_digits=15, verbose_name='Default price'),
        ),
    ]
