# Generated by Django 5.1.2 on 2025-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_salon_salon_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
    ]
