# Generated by Django 5.1.2 on 2024-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_salons_default_duration_salons_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text="JSON format: {'monday': {'open': '09:00', 'close': '18:00'}, ... }", verbose_name='Working Hours'),
        ),
    ]
