# Generated by Django 5.1.2 on 2024-11-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0013_appointment_barbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentbarberservice',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointmentbarberservice', to='salons.barber'),
        ),
    ]
