# Generated by Django 5.1.2 on 2024-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0014_alter_appointmentbarberservice_barber'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='default_duration',
            field=models.IntegerField(default=15, verbose_name='Default duration (minutes)'),
        ),
    ]
