# Generated by Django 5.1.2 on 2025-04-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0014_salon_additional_status_alter_salon_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='anyBarberMod',
            field=models.BooleanField(default=True, verbose_name='Any Barber Mod'),
        ),
    ]
