# Generated by Django 5.1.2 on 2024-11-29 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0015_servicecategory_default_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salon',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_salons', to=settings.AUTH_USER_MODEL),
        ),
    ]
