# Generated by Django 5.1.2 on 2025-04-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0015_salon_anybarbermod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='anyBarberMod',
            new_name='anyBarberMode',
        ),
    ]
