# Generated by Django 5.1.2 on 2025-04-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0016_rename_anybarbermod_salon_anybarbermode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='category',
            field=models.CharField(default='Beauty Salon', max_length=50, null=True, verbose_name='Category'),
        ),
    ]
