# Generated by Django 5.1.2 on 2024-12-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0017_barberavailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberavailability',
            options={},
        ),
    ]
