# Generated by Django 5.1.2 on 2025-05-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0017_salon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='additional_status',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('waiting_contact', 'Waiting for a contact'), ('mail', 'Mail'), ('they_think', 'They think'), ('not now', 'Not now'), ('ignored', 'Ignored'), ('expansion_needed', 'Expansion needed'), ('former_partner', 'Former Partner')], max_length=20, null=True, verbose_name='Additional Status'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in process', 'In process'), ('active', 'Active'), ('suspend', 'Suspend'), ('refused', 'Refused')], default='new', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='telegram_status',
            field=models.CharField(choices=[('new', 'New'), ('in process', 'In process'), ('active', 'Active'), ('suspend', 'Suspend'), ('refused', 'Refused')], default='active', max_length=10),
        ),
    ]
