# Generated by Django 5.1.2 on 2025-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0018_alter_salon_additional_status_alter_salon_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='additional_status',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('waiting_contact', 'Waiting for a contact'), ('mail', 'Mail'), ('they_think', 'They think'), ('not now', 'Not now'), ('not_interested', 'Not interested'), ('ignored', 'Ignored'), ('expansion_needed', 'Expansion needed'), ('former_partner', 'Former Partner')], max_length=20, null=True, verbose_name='Additional Status'),
        ),
    ]
