# Generated by Django 5.1.2 on 2024-12-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0018_alter_barberavailability_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='availability',
        ),
    ]
