# Generated by Django 5.1.2 on 2024-12-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0019_remove_barber_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='opening_hours',
        ),
    ]
