# Generated by Django 5.1.2 on 2025-09-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0019_alter_salon_additional_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='reservon_partner_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reservon Partner ID'),
        ),
    ]
