# Generated by Django 5.1.2 on 2024-12-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0020_remove_salon_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='bookng_minute',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Время бронирования'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий клиента'),
        ),
    ]
