# Generated by Django 5.1.2 on 2025-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0020_salon_reservon_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='jackbot_AI_mod',
            field=models.BooleanField(default=True, verbose_name='Jackbot AI mod'),
        ),
        migrations.AddField(
            model_name='salon',
            name='jackbot_format',
            field=models.CharField(choices=[('personal', 'Personal'), ('platfom', 'Platform')], default='personal', max_length=20, verbose_name='Jackbot format'),
        ),
    ]
