# Generated by Django 5.1.2 on 2024-12-31 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0021_appointment_bookng_minute_appointment_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='bookng_minute',
            new_name='booking_minute',
        ),
    ]
