# Generated by Django 5.1.2 on 2025-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0021_salon_jackbot_ai_mod_salon_jackbot_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='platform_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Platform name'),
        ),
    ]
