# Generated by Django 5.1.2 on 2025-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0022_salon_platform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Show in listings'),
        ),
    ]
