# Generated by Django 5.1.2 on 2025-01-02 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0022_rename_bookng_minute_appointment_booking_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='booking_minute',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
