# Generated by Django 5.1.2 on 2025-10-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0023_salon_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='salon',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='salon',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='salon',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='whatsapp'),
        ),
        migrations.AddField(
            model_name='salon',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='youtube'),
        ),
    ]
