# Generated by Django 5.1.2 on 2025-10-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0024_salon_email_salon_linkedin_salon_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='services_eng',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='services_hy',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='services_ru',
        ),
    ]
