# Generated by Django 5.1.2 on 2025-01-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0024_historicalappointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsalon',
            name='mod',
            field=models.CharField(choices=[('category', 'Category'), ('barber', 'Barber')], default='category', max_length=10),
        ),
        migrations.AddField(
            model_name='salon',
            name='mod',
            field=models.CharField(choices=[('category', 'Category'), ('barber', 'Barber')], default='category', max_length=10),
        ),
    ]
