# Generated by Django 5.1.2 on 2025-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0025_remove_salon_services_eng_remove_salon_services_hy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='default_booking_type',
            field=models.CharField(choices=[('service', 'Service'), ('event', 'Event')], default='service', max_length=10, verbose_name='Default Booking Type'),
        ),
    ]
