# Generated by Django 5.1.2 on 2025-01-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0025_historicalsalon_mod_salon_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(related_name='barbers', to='salons.service'),
        ),
    ]
