# Generated by Django 5.1.2 on 2025-01-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0024_historicalappointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='salons.service'),
        ),
    ]
