# Generated by Django 5.1.2 on 2025-01-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0028_barberservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='services',
        ),
    ]
