# Generated by Django 5.1.2 on 2025-01-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0029_remove_barber_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', through='salons.BarberService', to='salons.service'),
        ),
    ]
