# Generated by Django 5.1.2 on 2025-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0030_barber_services'),
    ]

    operations = [
        # Удаляем существующее поле services без 'through'
        migrations.RemoveField(
            model_name='barber',
            name='services',
        ),
        # Добавляем новое поле services с 'through=BarberService'
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='salons.Service', through='salons.BarberService'),
        ),
    ]
