# Generated by Django 5.1.2 on 2025-01-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0031_add_barberservice_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberservice',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
