# Generated by Django 5.1.2 on 2025-01-15 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0032_barberservice_duration_barberservice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='services',
        ),
        migrations.RemoveField(
            model_name='barberservice',
            name='service',
        ),
        migrations.AddField(
            model_name='appointmentbarberservice',
            name='barberServices',
            field=models.ManyToManyField(blank=True, to='salons.barberservice'),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_services', to='salons.servicecategory'),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/barberservices'),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='name',
            field=models.CharField(default='Service name', max_length=100),
        ),
        migrations.AddField(
            model_name='barberservice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointmentbarberservice',
            name='services',
            field=models.ManyToManyField(blank=True, to='salons.service'),
        ),
    ]
