# Generated by Django 5.1.2 on 2025-01-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0032_barberservice_duration_barberservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='default_duration',
            field=models.IntegerField(default=40, verbose_name='Default duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='default_duration',
            field=models.IntegerField(default=30, verbose_name='Default duration (minutes)'),
        ),
    ]
