# Generated by Django 5.1.2 on 2025-01-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0033_barber_default_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberservice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barber_services', to='salons.servicecategory'),
        ),
    ]
