# Generated by Django 5.1.2 on 2025-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0033_remove_barber_services_remove_barberservice_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='salons.service'),
        ),
    ]
