# Generated by Django 5.1.2 on 2025-01-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0033_barber_default_duration_and_more'),
        ('salons', '0034_barber_services'),
    ]

    operations = [
    ]
