# Generated by Django 5.1.2 on 2025-01-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0034_barber_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalappointmentbarberservice',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='historicalappointmentbarberservice',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='historicalappointmentbarberservice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbarber',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbarber',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='historicalbarber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalbarberavailability',
            name='barber',
        ),
        migrations.RemoveField(
            model_name='historicalbarberavailability',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsalon',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='barberservice',
            name='additional_info',
        ),
        migrations.DeleteModel(
            name='HistoricalAppointment',
        ),
        migrations.DeleteModel(
            name='HistoricalAppointmentBarberService',
        ),
        migrations.DeleteModel(
            name='HistoricalBarber',
        ),
        migrations.DeleteModel(
            name='HistoricalBarberAvailability',
        ),
        migrations.DeleteModel(
            name='HistoricalSalon',
        ),
        migrations.DeleteModel(
            name='HistoricalService',
        ),
    ]
