# Generated by Django 5.1.2 on 2025-01-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0035_merge_20250117_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='default_duration',
        ),
        migrations.AddField(
            model_name='salon',
            name='IsCheckDays',
            field=models.BooleanField(default=True, verbose_name='Is Check Days'),
        ),
        migrations.AddField(
            model_name='salon',
            name='mod',
            field=models.CharField(choices=[('category', 'Category'), ('barber', 'Barber')], default='category', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='default_duration',
            field=models.IntegerField(default=15, verbose_name='Default duration (minutes)'),
        ),
    ]
